/* Shared Good Mushroom navigation/footer for advisory pages. */
(function(){
  var page = document.body.getAttribute('data-page') || '';
  var nav = '<nav class="nav" aria-label="Main"><div class="nav-inner"><a href="https://goodmushroom.in/" class="nav-logo" aria-label="Good Mushroom — home"><span class="nav-logo-mark" aria-hidden="true"></span><span>Good Mushroom</span><img src="/images/logo-nav.png" alt="Good Mushroom" class="brand-img" width="343" height="96"></a><ul class="nav-links" role="list"><li><a href="https://goodmushroom.in/products.html">Products</a></li><li><a href="https://goodmushroom.in/about.html">About</a></li><li><a href="https://goodmushroom.in/buyers.html">Buyers</a></li><li><a href="https://goodmushroom.in/exports.html">Markets</a></li><li><a href="/">Advisory</a></li><li><a href="https://goodmushroom.in/contact.html">Contact</a></li></ul><div class="nav-cta"><a href="#request" class="btn btn-primary btn-sm">Request advisory</a><button class="nav-hamburger" aria-label="Open menu"><svg viewBox="0 0 24 24" width="20" height="20" fill="none" stroke="currentColor" stroke-width="2"><path d="M4 7h16M4 12h16M4 17h16"/></svg></button></div></div></nav><div class="mobile-menu" role="dialog" aria-label="Mobile menu"><div class="mobile-menu-top"><span class="nav-logo"><span class="nav-logo-mark"></span><span>Good Mushroom</span><img src="/images/logo-nav.png" alt="Good Mushroom" class="brand-img" width="343" height="96"></span><button class="mobile-menu-close" aria-label="Close menu">×</button></div><nav class="mobile-menu-links"><a href="/">Advisory home <span class="arr">→</span></a><a href="/services/mushroom-farm-dpr-india.html">Mushroom DPR <span class="arr">→</span></a><a href="/cordyceps-militaris-farming-business-plan-india.html">Cordyceps plan <span class="arr">→</span></a><a href="/resources/">Resources <span class="arr">→</span></a><a href="https://goodmushroom.in/">Trading &amp; supply <span class="arr">→</span></a></nav><div class="mobile-menu-foot"><a href="#request" class="btn btn-primary btn-lg">Request advisory →</a><a href="https://wa.me/918219599053" class="btn btn-outline btn-lg">Chat on WhatsApp</a></div></div>';
  var footer = '<footer class="foot"><div class="wrap"><div class="foot-grid"><div class="foot-brand"><img src="/images/logo-white.png" alt="Good Mushroom" class="brand-img" width="802" height="225"><h3>Good <em>Mushroom</em></h3><p>India-based functional mushroom sourcing, quality and advisory work—built around clearer commercial decisions.</p></div><div class="foot-col"><h5>Advisory</h5><ul><li><a href="/services/mushroom-farm-dpr-india.html">Mushroom farm DPR</a></li><li><a href="/cordyceps-militaris-farming-business-plan-india.html">Cordyceps business plan</a></li><li><a href="/mushroom-farming-cost-feasibility-india.html">Cost &amp; feasibility</a></li><li><a href="/mushroom-buyer-readiness-india.html">Buyer-readiness</a></li><li><a href="/resources/">Resources</a></li></ul></div><div class="foot-col"><h5>Good Mushroom</h5><ul><li><a href="https://goodmushroom.in/products.html">Products</a></li><li><a href="https://goodmushroom.in/buyers.html">For buyers</a></li><li><a href="https://goodmushroom.in/reports.html">Farming reports</a></li><li><a href="https://goodmushroom.in/privacy.html">Privacy</a></li></ul></div><div class="foot-col"><h5>Contact</h5><div class="foot-contact"><a href="mailto:info@goodmushroom.in">info@goodmushroom.in</a><a href="https://wa.me/918219599053">+91 82195 99053</a><span>Himachal Pradesh, India</span><span>Mon–Sat · 10am–6pm IST</span></div></div></div><div class="foot-bottom"><span>© 2026 Good Mushroom PVT LTD · All rights reserved</span><span>Good Mushroom Advisory</span></div></div></footer>';
  document.body.insertAdjacentHTML('afterbegin', nav);
  document.body.insertAdjacentHTML('beforeend', footer);
  var open = document.querySelector('.nav-hamburger'), menu = document.querySelector('.mobile-menu'), close = document.querySelector('.mobile-menu-close');
  if(open && menu){open.addEventListener('click',function(){menu.classList.add('open');document.body.style.overflow='hidden';});close.addEventListener('click',function(){menu.classList.remove('open');document.body.style.overflow='';});}
}());